// src/billingo/enums.ts
import { z } from 'zod';

/** Verbatim from spec/billingo-3.0.15.json → components.schemas.Currency.enum */
export const CURRENCIES = [
  'AED',
  'ALL',
  'AUD',
  'BGN',
  'BRL',
  'CAD',
  'CHF',
  'CNY',
  'COP',
  'CZK',
  'DKK',
  'EUR',
  'GBP',
  'GEL',
  'HKD',
  'HRK',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'ISK',
  'JPY',
  'KRW',
  'LEJ',
  'MKD',
  'MNT',
  'MXN',
  'MYR',
  'NOK',
  'NZD',
  'PHP',
  'PLN',
  'RON',
  'RSD',
  'RUB',
  'SEK',
  'SGD',
  'SKK',
  'THB',
  'TRY',
  'UAH',
  'USD',
  'ZAR',
] as const;
export const currencySchema = z.enum(CURRENCIES);

/** Verbatim from components.schemas.DocumentType.enum */
export const DOCUMENT_TYPES = [
  'advance',
  'cancellation',
  'cert_of_completion',
  'd_cert_of_completion',
  'dossier',
  'draft',
  'draft_offer',
  'draft_order_form',
  'draft_waybill',
  'invoice',
  'modification',
  'offer',
  'order_form',
  'proforma',
  'receipt',
  'receipt_cancellation',
  'waybill',
] as const;
export const documentTypeSchema = z.enum(DOCUMENT_TYPES);

/**
 * Verbatim from components.schemas.Vat.enum. Includes Hungarian special codes
 * (AAM, TAM, EU, ÁKK, ...) alongside percentages. Note the decimal comma in '25,5%'
 * and '5,5%' — that is the API's format, not a typo.
 */
export const VAT_RATES = [
  '0%',
  '1%',
  '10%',
  '11%',
  '12%',
  '13%',
  '14%',
  '15%',
  '16%',
  '17%',
  '18%',
  '19%',
  '2%',
  '20%',
  '21%',
  '22%',
  '23%',
  '24%',
  '25%',
  '25,5%',
  '26%',
  '27%',
  '3%',
  '4%',
  '5%',
  '5,5%',
  '6%',
  '7%',
  '7,7%',
  '8%',
  '8,1%',
  '9%',
  '9,5%',
  'AAM',
  'AM',
  'EU',
  'EUK',
  'F.AFA',
  'FAD',
  'K.AFA',
  'MAA',
  'TAM',
  'ÁKK',
  'ÁTHK',
] as const;
export const vatSchema = z.enum(VAT_RATES);

/** Verbatim from components.schemas.PaymentMethod.enum */
export const PAYMENT_METHODS = [
  'aruhitel',
  'bankcard',
  'barion',
  'barter',
  'cash',
  'cash_on_delivery',
  'cod_balance',
  'combined',
  'coupon',
  'credit',
  'ebay',
  'elore_utalas',
  'ep_kartya',
  'kompenzacio',
  'levonas',
  'online_bankcard',
  'other',
  'paylike',
  'payoneer',
  'paypal',
  'paypal_utolag',
  'payu',
  'pick_pack_pont',
  'postai_csekk',
  'postautalvany',
  'revolut',
  'skrill',
  'stripe',
  'szep_card',
  'transferwise',
  'upwork',
  'utalvany',
  'valto',
  'wire_transfer',
] as const;
export const paymentMethodSchema = z.enum(PAYMENT_METHODS);

/** Verbatim from components.schemas.Category.enum */
export const CATEGORIES = [
  'accounting_and_auditing',
  'advertisement',
  'bonus',
  'business_insurance',
  'cleaning',
  'construction_and_repair',
  'consulting',
  'consumer_goods',
  'contractors',
  'development',
  'dividends',
  'donations',
  'duty_taxes',
  'education_and_trainings',
  'electricity',
  'electronics',
  'employee_benefits',
  'entertainment',
  'equipment_insurance',
  'federal_taxes',
  'fees',
  'financials',
  'fines',
  'gas',
  'gas_and_fuel',
  'health_insurance',
  'human_resources',
  'income',
  'income_taxes',
  'insurance',
  'interest',
  'internet',
  'investments',
  'leasing',
  'legal',
  'liability_insurance',
  'loans',
  'meals',
  'mortgage',
  'office_rent',
  'online_subscriptions',
  'other',
  'overheads',
  'payroll_taxes',
  'phone',
  'prepayments',
  'professional_insurance',
  'property_taxes',
  'real_estate',
  'returns',
  'sales',
  'service',
  'service_and_parts',
  'shipping',
  'software',
  'staff_outsourcing',
  'stock',
  'storage',
  'supplies_and_furniture',
  'tangible_assets',
  'tax_return',
  'taxes',
  'taxi',
  'transport',
  'travel',
  'utilities',
  'vat',
  'vehicle_insurance',
  'wages',
  'water',
] as const;
export const categorySchema = z.enum(CATEGORIES);
